services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: agenda-app:latest  # Tag explícita
    container_name: agenda-app
    restart: unless-stopped
    volumes:
      - ./:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: agenda
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  npm:
    image: node:18
    container_name: npm
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
